apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: n58f0rfqf-go-gitops
  description: This is GitOps manifest for n58f0rfqf-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=n58f0rfqf-go
    backstage.io/kubernetes-id: n58f0rfqf-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: n58f0rfqf-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:n58f0rfqf-go
